### ISSUE TITLE
Could you please let me know why CIFAR dataset which is a image only dataset is used for Vi(video) VIT?

### ISSUE THREAD

**Issue by arunsubk** [KhanhSonPham/ViVit-a-Pytorch-implementation#3]
hi @KSonPham ,

Thanks for the repo. I was curious about why CIFAR dataset was used, which is an image-only dataset, and therefore the temporal dimension would not get used. Sorry but due to some constraints I haven't been able to check the code closely to understand any nuance, hence hoping to post this and get a direct answer if possible.

Thanks,
Arun

**Comment by KSonPham** [comment]
Hi @arunsubk,

I test CIFAR simply by stacking the same image twice. The main reason to do that is to test the learning capability of the model as testing with full video requires a lot of computational power :D.

Best,
Pham

**Comment by arunsubk** [comment]
Oh that's a cool way to do it. Understood. Thanks for the reply. :)

Regards,
Arun
