### ISSUE TITLE
ViViT test results

### ISSUE THREAD

**Issue by Claire874** [KhanhSonPham/ViVit-a-Pytorch-implementation#4]
hi @KSonPham

Thanks for the nice work in ViViT！
I am wondering did you train the video transformer (model 2) and test it on the public datasets or not.
If did, would you mind sharing the results and the best model?

Thanks for your great work!

**Comment by KSonPham** [comment]
Hi @Claire874 
since the model can use the weight from the official ViVit repo. The result should be comparable. At the time, I didn't have the required hardware so I designed this to make use of the given pre-trained weight which is in .npz format.

Best regard,
Pham

**Comment by Claire874** [comment]
Hi @KSonPham 
I got a question about embeddings, in your implementation. After the space transformer, I thought [cls]/mean values are fed forward to temporal transformers, but according to the code you provided, I didn't find that. it seems all representations are fed to temporal transformers.
